import {
	NEXT_PUBLIC_SUPABASE_URL,
	NEXT_PUBLIC_SUPABASE_ANON_KEY
} from '$env/static/public';

export const PUBLIC_SUPABASE_URL = NEXT_PUBLIC_SUPABASE_URL;
export const PUBLIC_SUPABASE_ANON_KEY = NEXT_PUBLIC_SUPABASE_ANON_KEY;
